# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        stages: [commit]
    -   id: end-of-file-fixer
        stages: [commit]
    -   id: check-yaml
        stages: [commit]
    -   id: debug-statements
        stages: [commit]
    -   id: name-tests-test
        stages: [commit]
        args: [--pytest-test-first]
    -   id: requirements-txt-fixer
        stages: [commit]
    -   id: check-added-large-files
        args: ['--maxkb=2000']
        stages: [commit]
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.7.0
    hooks:
    -   id: setup-cfg-fmt
        stages: [commit]

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
        stages: [commit]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
    -   id: pyupgrade
        args: [--py311-plus]
        stages: [commit]

-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        stages: [commit]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    -   id: mypy
        stages: [commit]
        pass_filenames: false
        args: ['culicidaelab']
        additional_dependencies:
        - types-requests
        - types-PyYAML
        - types-toml
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
    -   id: bandit
        stages: [commit]
        args: [--configfile, .bandit, '--exclude', 'tests/']
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
    -   id: ruff-format
        stages: [commit]
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
        require_serial: true
        stages: [commit]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: ["--line-length", "120"]
        stages: [commit]
