# provider_url: "https://datasets-server.huggingface.co/croissant-crumbs?dataset={dataset_name}"
# api_key: "{api_key}"
_target_: "culicidaelab.providers.HuggingFaceProvider"
provider_url: "https://datasets-server.huggingface.co/croissant-crumbs?dataset={dataset_name}"
