# defaults:
#   model_arch: "yolov11n"
#   weights:
#     local_path: "weights/detection/culico-net-det-v1-nano.pt"
#     remote_repo: "iloncka/culico-net-det-v1"
#     remote_file: "culico-net-det-v1-nano.pt"
#   dataset_repository: "iloncka/mosquito-species-detection-dataset"
#   params:
#     confidence_threshold: 0.25
#     iou_threshold: 0.45
#     max_detections: 1
_target_: "culicidaelab.predictors.Detector"
model_path: "weights/detection/culico-net-det-v1-nano.pt"
confidence: 0.25
device: "auto"
params:
  iou_threshold: 0.45
  max_detections: 1
model_arch: "yolov11n"
dataset_repository: "iloncka/mosquito-species-detection-dataset"
