species:
  metadata:
    Aedes aegypti:
      color: yellow
      region: tropical
    Anopheles gambiae:
      color: brown
      region: Africa
  species_map:
    0: Aedes aegypti
    1: Anopheles gambiae
