name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material[i18n]==9.5.46 mkdocstrings[python]==0.27.0
      - run: pip install mkdocs-custom-fences==0.1.2 mkdocs-gallery>=0.10.4
      - run: mkdocs build --config-file=mkdocs.en.yml --clean -d site/en
      - run: mkdocs build --config-file=mkdocs.ru.yml --dirty -d site/ru
      - run: mkdocs gh-deploy --force --dirty --config-file=mkdocs.en.yml
      - run: mkdocs gh-deploy --force --dirty --config-file=mkdocs.ru.yml
